In [ ]:

#Import the numpy library as np.
import numpy as np

In [ ]:
#Convert list [10, 20, 30, 40, 50] to a NumPy array. Print its type.
ar = np.array([10, 20, 30, 40, 50])
print(ar)
print(type(ar))


[10 20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
#Create a 2D NumPy array from the list: [[1, 2, 3], [4, 5, 6]]. Print it.
ar = np.array([[1, 2, 3], [4, 5, 6]])
print(ar)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Print the shape, number of dimensions, size, and data type of the 2D array from Q3.
ar_2d =np.array([[1, 2, 3], [4, 5, 6]])
print("shape:",ar_2d.shape)
print("Dimension:",ar_2d.ndim)
print("size:",ar_2d.size)
print("data_type:",ar_2d.dtype)

shape: (2, 3)
Dimension: 2
size: 6
data_type: int64


In [ ]:
#Create an array of 10 zeros using np.zeros().
import numpy as np
zero_ar =np.zeros(10)
print(zero_ar)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#Create a 3x3 matrix of ones using np.ones().
import numpy as np
one_ar = np.ones((3,3),dtype=int)
print(one_ar)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#Generate an array of numbers from 10 to 50 with a step of 2 using np.arange().
import numpy as np
arr = np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
#Create an array of 5 values spaced equally between 0 and 1 using np.linspace().
import numpy as np
arr = np.linspace(0,1,5)
print(arr)


[0.   0.25 0.5  0.75 1.  ]


In [ ]:
#Convert an integer NumPy array to a float array using astype().
import numpy as np
int_arr = np.array([1,2,3])
print(int_arr,int_arr.dtype)

float_arr = int_arr.astype(float)
print("new:",float_arr,float_arr.dtype)

[1 2 3] int64
new: [1. 2. 3.] float64


In [ ]:
# Explain in comments why NumPy arrays are faster and more efficient than Python lists.
# 1. less memory when compared to python lists
# 2.vector operations
# 3.fixed & homogeneous data


[0.  0.2 0.4 0.6 0.8]


In [ ]:
#Create a NumPy array [1, 2, 3] and multiply all elements by 5 using broadcasting.
import numpy as np
arr= np.array([1,2,3])
product = arr*5
print(product)

[ 5 10 15]


In [ ]:
#Add two NumPy arrays element-wise: [10, 20, 30] and [1, 2, 3].
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([1, 2, 3])
sum = arr1 + arr2
print(sum)

[11 22 33]


In [ ]:
#Given 2D array: matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]]), extract the element at row index 1, column index 2.
import numpy as np
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
element = matrix [1,2]
print(element)


60


In [ ]:
#Slice the first two rows and last two columns from matrix in Q3.
import numpy as np
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
Q3 = matrix[0:2,-2:]
print(Q3)


[[20 30]
 [50 60]]


In [ ]:
#Find the sum, mean, and standard deviation of all elements in matrix.
import numpy as np
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
sum = matrix.sum()
mean = matrix.mean()
std_dev = matrix.std()

print(sum)
print(mean)
print(std_dev)



450
50.0
25.81988897471611


In [ ]:
#Find the maximum value of each column in matrix (hint: use axis parameter).
import numpy as np
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
max_value = matrix.max(axis=0)
print(max_value)


[70 80 90]


In [ ]:
#Find the minimum value of each row in matrix.
import numpy as np
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
min_value = matrix.min(axis=1)
print(min_value)

[10 40 70]


In [1]:
#Reshape a 1D array [1, 2, 3, 4, 5, 6, 7, 8] into a 2D array of shape (2, 4).
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
new_arr = arr.reshape(2,4)
print(new_arr)


[[1 2 3 4]
 [5 6 7 8]]


In [5]:
#Flatten a 2D array back into a 1D array using ravel() or flatten().
import numpy as np
old_arr = new_arr.ravel()
print(old_arr)

[1 2 3 4 5 6 7 8]


In [12]:
#Given an array of student marks [55, 62, 48, 75, 90, 82, 38, 60],
# calculate the percentage of students who passed (passing mark is 50)
#using NumPy conditional expressions.
import numpy as np
marks = np.array([55, 62, 48, 75, 90, 82, 38, 60])
pass_stu = marks >= 50
pass_percentage = np.mean(pass_stu)*100
print(pass_percentage)





75.0
